/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function Model(props: any) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/models/animated_character.gltf') as any;
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    console.log(actions);
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="HG_Melissa">
          <primitive object={nodes.spine} />
          <skinnedMesh
            name="HG_Body"
            geometry={nodes.HG_Body.geometry}
            material={materials['.Human']}
            skeleton={nodes.HG_Body.skeleton}
          />
          <skinnedMesh
            name="HG_Running_Shoe_1_Female001"
            geometry={nodes.HG_Running_Shoe_1_Female001.geometry}
            material={materials['.HG_Running_Shoe_1.001']}
            skeleton={nodes.HG_Running_Shoe_1_Female001.skeleton}
          />
          <skinnedMesh
            name="HG_Skinny_Jeans_Female001"
            geometry={nodes.HG_Skinny_Jeans_Female001.geometry}
            material={materials['.HG_Skinny_Jeans.008']}
            skeleton={nodes.HG_Skinny_Jeans_Female001.skeleton}
          />
          <skinnedMesh
            name="HG_TSHIRT_Female001"
            geometry={nodes.HG_TSHIRT_Female001.geometry}
            material={materials['.HG_TSHIRT.006']}
            skeleton={nodes.HG_TSHIRT_Female001.skeleton}
          />
          <group name="HG_Eyes">
            <skinnedMesh
              name="Mesh_1"
              geometry={nodes.Mesh_1.geometry}
              material={materials['.HG_Eyes_Outer_FAST']}
              skeleton={nodes.Mesh_1.skeleton}
            />
            <skinnedMesh
              name="Mesh_2"
              geometry={nodes.Mesh_2.geometry}
              material={materials['.HG_Eyes_Inner']}
              skeleton={nodes.Mesh_2.skeleton}
            />
          </group>
          <skinnedMesh
            name="HG_TeethLower"
            geometry={nodes.HG_TeethLower.geometry}
            material={materials['.HG_Teeth']}
            skeleton={nodes.HG_TeethLower.skeleton}
          />
          <skinnedMesh
            name="HG_TeethUpper"
            geometry={nodes.HG_TeethUpper.geometry}
            material={materials['.HG_Teeth']}
            skeleton={nodes.HG_TeethUpper.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/animated_character.gltf');
